### ISSUE TITLE
Direction arrows sometimes point in wrong direction

### ISSUE THREAD

**Issue by tyrasd** [Telenav/scoutsigns#2]
The driving direction arrows sometimes appear to point in the wrong direction. See for example scout signs with id 209388 or 221440.

**Comment by tyrasd** [comment]
any news on this one, @mvexel?

**Comment by beataj-telenav** [comment]
We have investigated these 2 road signs and it seams that the collected heading value is incorrect (we draw the direction based on the heading collected by the clients). Do you have any other examples for which the direction is invalid?

**Comment by tyrasd** [comment]
Here are a couple of more examples (there seem to be quite many…):
* 235274
* 212322
* 221440
* 131654
* 144220
* 207281
* 221103

**Comment by beataj-telenav** [comment]
Thanks. I will compute the heading instead of using the reported one.
